;;; org-outlook-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-outlook.el

(autoload 'org-outlook-open "org-outlook" "\
Open the Outlook item identified by ID.  ID should be an Outlook GUID.

(fn ID)")
(autoload 'org-outlook-create-vbs "org-outlook" "\
Creates Visual Basic Code for Org-protocol" t)
(eval-after-load "org" '(org-add-link-type "outlook" 'org-outlook-open))
(autoload 'org-protocol-outlook "org-outlook" "\
Process an org-protocol://outlook:// style url.

The sub-protocol used to reach this function is set in
`org-protocol-protocol-alist'.

This function detects the Message ID, Subject, Sender and
optional text separated by '/'.  For example either

org-protocol://outlook:/ID/Subject/SenderName/SenderAddress

or

org-protocol://outlook:/o/ID/Subject/SenderName/SenderAddress

works.

By default, it uses the character
`org-protocol-outlook-default-template-key', which should be associated
with a template in `org-capture-templates'.

To use this plugin:
- Copy the outlook macro (below) into outlook
- Modify the outlook capture template (o) to capture the email as
  a task. An example is below.


 (\"o\" \"org-outlook\" entry (file \"~/org/refile.org\") \"* TODO Email %c %?
  %i
  %U\" :clock-in t :clock-resume t)

You may also use the following placeholders

Placeholders Replacement 
%:link URL of the email
%:description The title of the message
%:title The title of the message 
%:initial Selected text.
%:sender Sender's name
%:sender-email Sender's Email

- (optional) Modify the folder/location that outlook moves mail into (moving
  mail off the server changes the message ID.  Once off the
  server, the ID remains the same unless you move it back...)
- (optional) Modify the capture template used (I use ``o'')
- (optional) Make the macro CreateTaskFromItem accessable
  anywhere from outlook by adding it to the quick access toolbar
  and/or the standard toolbar.

(fn INFO)")
(autoload 'org-outlook-enable-msg-dnd "org-outlook" "\
Enable Drag and Drop support for message files." t)
(autoload 'org-protocol-do-outlook-capture "org-outlook" "\
Support `org-capture' and `org-remember' alike.
CAPTURE-FUNC is either the symbol `org-remember' or `org-capture'.

(fn INFO CAPTURE-FUNC)")
(eval-after-load "org-protocol" '(progn (if (not (boundp 'org-protocol-protocol-alist)) (setq org-protocol-protocol-alist nil)) (add-to-list 'org-protocol-protocol-alist '("outlook" :protocol "outlook" :function org-protocol-outlook :kill-client t))))
(register-definition-prefixes "org-outlook" '("org-"))

;;; End of scraped data

(provide 'org-outlook-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-outlook-autoloads.el ends here
